### ISSUE TITLE
MSB and LSB

### ISSUE THREAD

**Issue by pboling** [amiel/bitmask#5]
Add `msb` and `lsb` methods to return the most and least significant bits, respectively.

**Comment by pboling** [comment]
@amiel Glad you saw and liked the other one.  What do you think of this one?

**Comment by amiel** [comment]
Hi @pboling. I was actually on the road yesterday. It was easy to quickly understand your other PR on my phone.

Could you explain your use-case on this one? I'm not against merging it, but I'd like to understand why this would be useful. I guess I understand _what_ it does, just not _why_.

Also, I guess only sort of related, but I haven't used this gem in quite a while. Since you are using it, and have some ideas, do you have any interest in helping maintain it?

**Comment by pboling** [comment]
> Since you are using it, and have some ideas, do you have any interest in helping maintain it?

Definitely interested in helping maintain it.  I actually maintain one of the oldest, but still popular, ruby bitmask ORM libraries, `flag_shih_tzu`, similar to your `bitmasker`.  I've thought about refactoring `flag_shih_tzu` to use `bitmask` internally...

> Could you explain your use-case on this one?

My current use case is using the bitmask to allow simple determination of which `true` "flag" / "bit" has the highest, or lowest, precedence.  This is useful when using the bitmask to store a set of attributes which, in addition to each being true or false, are also correlated in a hierarchy, like an ordered list.  I want to know the `true` attribute with the highest, or lowest bit set.

In my use case it is for use with authorization roles where a user could have multiple roles. All roles would be in a strict hierarchy for certain purposes.  In my use case it is determining which "root path" a user sees as their homepage, based on the "highest" role they have.

**Comment by amiel** [comment]
That makes sense, and I like it. It seems like a `most_significant_flag # @return [Symbol]` would also be useful. Anyway, based on your interest and your track record, I've invited you to be a collaborator and you should be able to merge #6.

**Comment by pboling** [comment]
Yeah, I thought about going that direction too :) Perhaps that might also be useful.  Thanks!
